services:
  - type: web
    name: cloud-blog
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn cloud_blog.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: fd-8y-3mpo(f(+7-s+n@$-4l1m#8=fxvk7isxb&2zn*s-^!)l*
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: cloud-blog.onrender.com
